### ISSUE TITLE
[bug?]B站疑似对未登陆用户做了限制，五分钟后获取的id全为0，名称打码

### ISSUE THREAD

**Issue by RemKeeper** [Akegarasu/blivedm-go#10]
![76725241cf6fb56591595bbed2ab1dfd](https://github.com/Akegarasu/blivedm-go/assets/78486275/8fc63f7c-dc2e-41d2-b769-17837353d6ac)

ws中携带的的用户信息
![image](https://github.com/Akegarasu/blivedm-go/assets/78486275/f4212350-59bc-4407-83d8-c666fb0d6031)

已知buvid对应cookie中的buvid3
key对应token

请问这个库留有相关的定义接口吗？

**Comment by tymon42** [comment]
已经提了 PR #11，或者可以先用我的 [fork](https://github.com/tymon42/blivedm-go)
