### ISSUE TITLE
丢失弹幕

### ISSUE THREAD

**Issue by hajime-early** [Akegarasu/blivedm-go#15]
丢失弹幕的概率特别大。似乎这下需要真的挂个Cookie进去了。

**Comment by Akegarasu** [comment]
related
- https://github.com/xfgryujk/blivedm/issues/33
- https://github.com/simon300000/bilibili-live-ws/issues/401

solution
- https://github.com/simon300000/bilibili-live-ws/issues/397#issuecomment-1617901764

**Comment by Akegarasu** [comment]
经测试，携带buvid仍然丢失率很高，但疑似和弹幕服务器有关
