### ISSUE TITLE
哥们，你发送心跳包时有问题, 导致认证失效无法正常收到弹幕。

### ISSUE THREAD

**Issue by malubaka** [Akegarasu/blivedm-go#20]
你发送心跳包 []byte{0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 2, 0, 0, 0, 1}没有带p.ProtocolVersion，导致认证失效无法正常收到弹幕。

**Comment by Akegarasu** [comment]
1. 认证、接收弹幕均与心跳包无关
2. 这根本不是心跳包

**Comment by malubaka** [comment]
![danmu](https://github.com/Akegarasu/blivedm-go/assets/147259023/0052b9e5-8779-49e8-b940-bf0a15a876d4)

**Comment by malubaka** [comment]
我确实不该随意推断问题出在哪，心跳包那个我也确实打错了。
但是这个问题也确确实实存在。
我用的是v1.5.0版本，上面图片显示发送心跳包之后 ，名字就不显示了。
但你既然这么有底气说没关系，那我觉得你跑代码时应该也是没问题的。
我就直接把你项目下来，在你的项目运行代码，确实没问题，一切正常。
那是不是打包出了问题我也不明白，但这个问题确实存在。

**Comment by Akegarasu** [comment]
https://github.com/Akegarasu/blivedm-go/issues/15#issuecomment-1703843538
