### ISSUE TITLE
[询问]有判断弹幕发送者是否为舰长的字段吗

### ISSUE THREAD

**Issue by RemKeeper** [Akegarasu/blivedm-go#9]
我尝试过判断用户名字颜色，但是无法定位到#00D1F1这个值在哪个字段中
![image](https://user-images.githubusercontent.com/78486275/195989675-19cf71a3-f740-4b45-aed5-239f90be0816.png)

加上我发现好像还有紫色名字的贵宾，如果还有更高层次的反而无法准确判断了

**Comment by Akegarasu** [comment]
`Danmaku.Sender.GuardLevel`

**Comment by RemKeeper** [comment]
非常感谢~
